# 通过ServiceEntry配置可访问的外部接口
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: github-external
spec:
  hosts:
  - github.com
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL