# data format
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: my-password-data
data:
  password: bXlzcWxwYXNzd29yZAo=   # value经过base64编码

---
# stringdata format
apiVersion: v1
kind: Secret
metadata:
  name: my-password-stringdata
type: Opaque
stringData:
  password: mysqlpassword