piVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello-world
  namespace: default-injection
spec:
  hosts:
    - "*"  # 外部host的域名访问控制， 允许任何域名
  gateways:
    - gateway
  http:
    - route:
        - destination:  # matched svc
            host: hello-world.default-injection.svc.cluster.local
            port:
              number: 80